image: alpine/edge
packages:
  - rsync
  - hugo
sources:
  - https://git.sr.ht/~mjorgensen/live.jrgnsn.net
secrets:
  - 
tasks:
- build: |
    cd live.jrgnsn.net
    hugo
- upload: |
    cd live.jrgnsn.net
    echo "StrictHostKeyChecking=no" >> ~/.ssh/config
    rsync -rP public/ deploy@live.jrgnsn.net:/var/www/live.jrgnsn.net/
